title: PS C:\Users\psbootcamp> _
description: A Challenger Series for PowerShell bootcamp readers community

baseurl: /psbootcamp-blog

show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
